const products = [
    {
      id: 0,
      name: "Tonkotsu Ramen",
      price: 100.00,
      instock: 100,
      imgSrc: "../assets/R1.jpg",
    },
    {
      id: 1,
      name: "Miso Ramen",
      price: 110.00,
      instock: 100,
      imgSrc: "../assets/R2.jpg",
    },
    {
      id: 2,
      name: "Shoyu Ramen",
      price: 120.00,
      instock: 100,
      imgSrc: "../assets/R3.jpg",
    },
    {
        id: 3,
        name: "Shio Ramen",
        price: 130.00,
        instock: 100,
        imgSrc: "../assets/R4.jpg",
    },
    {
        id: 4,
        name: "Tsukemen Ramen",
        price: 110.00,
        instock: 100,
        imgSrc: "../assets/R5.jpg",
    },
    {
        id: 5,
        name: "Wakayama Ramen",
        price: 100.00,
        instock: 100,
        imgSrc: "../assets/R6.jpg",
    },
    {
        id: 6,
        name: "Abura Soba Ramen",
        price: 125.00,
        instock: 100,
        imgSrc: "../assets/R7.jpg",
    },
    {
      id: 7,
      name: "Kitakata Ramen",
      price: 115.00,
      instock: 100,
      imgSrc: "../assets/R8.jpg",
  },
  {
      id: 8,
      name: "Sapporo Ramen",
      price: 110.00,
      instock: 100,
      imgSrc: "../assets/R9.jpg",
  },
]